services:
  api:
    image: sugarbar-api:dev
    pull_policy: build
    build:
      context: ./api
      dockerfile: Dockerfile
    command:
      [
        "uv",
        "run",
        "fastapi",
        "run",
        "app/main.py",
        "--proxy-headers",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]
    ports:
      - "8001:8000"
    volumes:
      - /home/sammi/.youtube_cookies.txt:/root/.youtube_cookies.txt
      - /home/sammi/.crawl4ai/profiles/musixmatch-login:/root/.crawl4ai/profiles/musixmatch
      - /root/.Xauthority:/root/.Xauthority:ro
    environment:
      - YOUTUBE_COOKIES_PATH=/root/.youtube_cookies.txt
      - MUSIXMATCH_PROFILE_PATH=/root/.crawl4ai/profiles/musixmatch
      - DISPLAY=localhost:10.0
      - XAUTHORITY=/root/.Xauthority
    env_file: .env
    develop:
      watch:
        - action: sync
          path: ./api
          target: /app
          initial_sync: true
          ignore:
            - .venv/
            - __pycache__/
            - .pytest_cache/
            - .mypy_cache/
            - .ruff_cache/
        - action: rebuild
          path: ./api/pyproject.toml
        - action: rebuild
          path: ./api/uv.lock

  frontend:
    image: sugarbar-frontend:dev
    pull_policy: build
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_CONVEX_URL: http://127.0.0.1:3210
    ports:
      - "3001:3000"
    env_file: .env
    develop:
      watch:
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./pnpm-lock.yaml
        - action: rebuild
          path: ./src
        - action: rebuild
          path: ./public
        - action: rebuild
          path: ./vite.config.ts
        - action: rebuild
          path: ./tsconfig.json
