services:
  api:
    image: sugarbar-api:dev
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - /home/sammi/.youtube_cookies.txt:/root/.youtube_cookies.txt
      - /home/sammi/.crawl4ai/profiles/musixmatch-login:/root/.crawl4ai/profiles/musixmatch
      - /root/.Xauthority:/root/.Xauthority:ro
    environment:
      - YOUTUBE_COOKIES_PATH=/root/.youtube_cookies.txt
      - MUSIXMATCH_PROFILE_PATH=/root/.crawl4ai/profiles/musixmatch
      - DISPLAY=localhost:10.0
      - XAUTHORITY=/root/.Xauthority
    env_file: .env

  frontend:
    image: sugarbar-frontend:dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_CONVEX_URL: http://127.0.0.1:3210
    ports:
      - "3001:3000"
    env_file: .env
