services:
  api:
    # build:
    #   context: ./api
    #   dockerfile: Dockerfile
    image: ghcr.io/5ammiches/sugarbar-api:latest
    ports:
      - "8000:8000"
    environment:
      - DISPLAY=host.docker.internal:0
      - MUSIXMATCH_PROFILE_PATH=/root/.crawl4ai/profiles/musixmatch
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - c4ai_chrome_profile:/root/.crawl4ai/profiles/musixmatch
    env_file:
      - .env

  cloudflared:
    profiles: ["dev"]
    image: cloudflare/cloudflared:latest
    command: tunnel --url http://api:8000
    depends_on:
      - api
    restart: unless-stopped

  frontend:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     VITE_CONVEX_URL: ${VITE_CONVEX_URL}
    image: ghcr.io/5ammiches/sugarbar-api:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - api

volumes:
  c4ai_chrome_profile:
