name: Build and Deploy

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build/push frontend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            VITE_CONVEX_URL=${{ secrets.VITE_CONVEX_URL }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-frontend:latest
            ghcr.io/${{ github.repository }}-frontend:${{ github.sha }}

      - name: Build/push api
        uses: docker/build-push-action@v6
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-api:latest
            ghcr.io/${{ github.repository }}-api:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Coolify redeploy (with retries)
        run: |
          for i in 1 2 3; do
            curl --fail --show-error --location \
              -request GET "${{ secrets.COOLIFY_WEBHOOK }}" \
              --header "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}" && break
            echo "Retrying in 5s..."
            sleep 5
          done

          # YUP
          # for i in 1 2 3; do
          #   curl --fail --show-error --location \
          #     -X POST "${{ secrets.COOLIFY_WEBHOOK }}" \
          #     --header "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}" && break
          #   echo "Retrying in 5s..."
          #   sleep 5
          # done
