name: Build and Deploy

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        svc:
          - name: frontend
            context: .
            file: ./Dockerfile
            image: ghcr.io/${{ github.repository }}-frontend
          - name: fastapi
            context: ./api
            file: ./Dockerfile
            image: ghcr.io/${{ github.repository }}-api
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.svc.context }}
          file: ${{ matrix.svc.file }}
          push: true
          tags: |
            ${{ matrix.svc.image }}:latest
            ${{ matrix.svc.image }}:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Redeploy
        run: |
          curl -fsSL -X GET "${{ secrets.COOLIFY_WEBHOOK }}" \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}"
